# Generated by Django 5.0.6 on 2024-06-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=550)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField()),
                ('publish_time', models.DateField()),
            ],
        ),
    ]
